big ol update

diff --git a/.config/zsh/aliases b/.config/zsh/aliases
--- a/.config/zsh/aliases
+++ b/.config/zsh/aliases
@@ -12,7 +12,7 @@ alias lta="ls -lrtAh"
 # -------------
 chpwd() { ll }            # cd and ls
 mc() { mv $@ && ${(P)#} } # mv and cd
-cc() { cp $@ && ${(P)#} } # cp and cd
+# cc() { cp $@ && ${(P)#} } # cp and cd
 
 # compression
 # -----------
@@ -40,7 +40,37 @@ loop() {
     while sleep "$time"; do clear; $@; done
 }
 
-alias usv='SVDIR=$USER_SVDIR sv'
+rmlink(){ [ -L "$1" ] && rm -v "$1" }
+
+usv_enable() {
+    [ -z "$1" ] && { echo "missing service arg" >&2; return 1 }
+    [ -d "$USER_SVDIR/$1" ] || { echo "no such service '$1'" >&2; return 1 }
+    [ -L "$USER_SVDIR/enabled/$1" ] && { echo "service '$1' is already enabled" >&2; return 1 }
+    echo ln -s "../$1" "$USER_SVDIR/enabled/"
+    ln -s "../$1" "$USER_SVDIR/enabled/"
+}
+__usv() {
+    case "$1" in
+        'enable')
+            shift
+            # expand the $@ args into an array here, handling globs/multiple service names/etc.
+            # the `perl` command prefixes every wenv with $XDG_CONFIG_HOME/sv so we can expand based on what's in that directory,
+            # while the `eval echo` handles the actual expansion
+            local service_dirs=($(eval echo $(perl -pe "s|([^ ]+)|$XDG_CONFIG_HOME/sv/\1|g" <<< $@)))
+            for s in $service_dirs; do usv_enable $(basename $s); done
+            ;;
+        'disable')
+            shift
+            local enabled_services=($(eval echo $(perl -pe "s|([^ ]+)|$XDG_CONFIG_HOME/sv/enabled/\1|g" <<< $@)))
+            for s in $enabled_services; do rmlink $s; done
+            ;;
+        *)
+            SVDIR=$USER_SVDIR sv $@
+            ;;
+    esac
+}
+alias usv='noglob __usv'
+
 alias tm="tmux attach"
 alias kak='kak_session'
 alias apv='mpv --vid=no'
@@ -48,6 +78,7 @@ alias ts='tabbed -c -r2 surf -e x -SN'
 alias xc='xclip -selection c'
 alias fd='/usr/bin/fd --hidden'
 alias ag="/usr/bin/ag --color-path='1;36' --color-line-number='0;37' --color-match='1;33' --hidden --ignore node_modules --ignore .git"
+alias lg=lazygit
 
 # curl with status code
 alias scurl='curl -w "%{http_code}"'
